<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>JavaScript Execution Context Demo</title>
		<style>
			body {
				font-family: Arial, sans-serif;
			}
		</style>
	</head>
	<body>
		<script>
			// 使用 Promise.myAll
			Promise.myAll = function (promises) {
				let allRes = new Array(promises.length).fill(undefined);
				let count = 0;
				return new Promise((resolve, reject) => {
					if (promises.length === 0) {
						resolve([]);
					}
					for (let i = 0; i < promises.length; i++) {
						promises[i]
							.then(res => {
								allRes[i] = res;
								count++;
								if (count === promises.length) {
									resolve(allRes);
								}
							})
							.catch(err => {
								reject(err);
							});
					}
				});
			};
			let promise1 = new Promise((res, rej) => {
				setTimeout(() => {
					res('p1调用成功');
				}, 2500);
			});

			//p2: 直接转化为res状态
			let promise2 = new Promise((res, rej) => {
				res('p2调用成功');
			});

			//p3: 1s后转化为rejected状态
			let promise3 = new Promise((res, rej) => {
				setTimeout(() => {
					rej('p3失败了...');
				}, 1000);
			});

			//p4: 2s后转化为rejected状态
			let promise4 = new Promise((res, rej) => {
				setTimeout(() => {
					rej('p4失败了...');
				}, 2000);
			});
			let promise5 = new Promise((res, rej) => {
				setTimeout(() => {
					res('p5调用成功');
				}, 500);
			});
			Promise.myAll([promise1, promise2, promise5])
				.then(values => {
					console.log('Promise.myAll resolved values:', values);
				})
				.catch(error => {
					console.log('Promise.myAll was rejected with error:', error);
				});

			// 测试 Promise.myAll
			Promise.myAll([promise1, promise2, promise4])
				.then(values => {
					console.log('Promise.myAll resolved values:', values);
				})
				.catch(error => {
					console.log('Promise.myAll was rejected with error:', error);
				});

			Promise.myAll([promise3, promise1, promise2])
				.then(values => {
					console.log('Promise.myAll resolved values:', values);
				})
				.catch(error => {
					console.log('Promise.myAll was rejected with error:', error);
				});

			Promise.myRace = function (promises) {
				return new Promise((resolve, reject) => {
					for (let i = 0; i < promises.length; i++) {
						promises[i]
							.then(res => {
								resolve(res);
							})
							.catch(err => {
								reject(err);
							});
					}
				});
			};

			// 测试 Promise.myRace
			Promise.myRace([promise1, promise2, promise4])
				.then(value => {
					console.log('Promise.myRace resolved with value:', value);
				})
				.catch(error => {
					console.log('Promise.myRace was rejected with error:', error);
				});

			Promise.myRace([promise3, promise1])
				.then(value => {
					console.log('Promise.myRace resolved with value:', value);
				})
				.catch(error => {
					console.log('Promise.myRace was rejected with error:', error);
				});
		</script>
	</body>
</html>
